// Conteúdo do portfólio. Para adicionar um projeto novo, basta incluir
// um objeto em PROJETOS (e os screenshots em public/shots/<slug>.webp e
// <slug>-mobile.webp) — a grade, os filtros e a página do projeto são
// gerados a partir daqui.

export const PERFIL = {
  nome: 'Pedro Acácio',
  titulo: 'Sites e apps sob medida',
  bio: 'Crio landing pages e aplicações web para negócios reais — da identidade visual da marca até o site no ar, com domínio, WhatsApp e formulários funcionando.',
  cidade: 'Fortaleza, CE',
  github: 'https://github.com/pedro-acacio',
  // Preencha para exibir os botões de contato no site:
  email: '',
  whatsapp: 'https://wa.me/5585996039656',
  linkedin: 'https://www.linkedin.com/in/pedro-ac%C3%A1cio-72116/',
  instagram: 'https://www.instagram.com/paneto__/',
}

export const TIPOS = ['Todos', 'Landing page', 'Aplicação web']

export const PROJETOS = [
  {
    slug: 'mahut',
    nome: 'Mahut Arquitetura',
    tipo: 'Landing page',
    cliente: 'Lara Silveira, arquiteta e urbanista',
    local: 'Fortaleza, CE',
    ano: 2026,
    resumo: 'Site institucional de um escritório de arquitetura e interiores focado em neuroarquitetura e biofilia.',
    desafio: 'Traduzir um manual de marca sofisticado em uma página que transmitisse calma e atemporalidade — e que transformasse visitantes em pedidos de proposta qualificados.',
    entregas: [
      'Identidade aplicada a partir do manual da marca: paleta terrosa, tipografia serifada e a logo animada na seção de conceito',
      'Portfólio de projetos com renders reais do escritório',
      'Assistente de solicitação de proposta em etapas, nativo no site, que chega pronto no WhatsApp',
      'Layout responsivo revisado para celular, com animações de entrada suaves',
    ],
    stack: ['React', 'Vite', 'Tailwind CSS v4', 'Vercel'],
    paleta: ['#e8ded3', '#a15d3f', '#464b2e', '#544840'],
    fontes: 'Fraunces · Montserrat',
    cor: '#a15d3f',
    fundo: '#e8ded3',
    url: 'https://mahut-arquitetura.vercel.app',
  },
  {
    slug: 'hifive',
    nome: 'Hifive Discos & Bar',
    tipo: 'Landing page',
    cliente: 'Loja de discos de vinil e bar',
    local: 'Meireles, Fortaleza, CE',
    ano: 2026,
    resumo: 'Loja de vinil de dia, bar com discotecagem à noite — uma página com a cara de um lado A.',
    desafio: 'Um negócio com duas personalidades precisava de um site só, que levasse tanto ao catálogo online quanto ao balcão do bar.',
    entregas: [
      'Paleta extraída da logo real: só creme e preto, como a identidade da casa',
      'Disco de vinil interativo no topo — toque para tocar',
      'Modo claro/escuro automático, seguindo o sistema do visitante',
      'Seções organizadas como faixas de um disco, com catálogo, galeria, localização e links',
    ],
    stack: ['React', 'Vite', 'Tailwind CSS', 'Vercel'],
    paleta: ['#fffbe0', '#e6dfb8', '#1d1a17', '#131110'],
    fontes: 'Zilla Slab · Work Sans · JetBrains Mono',
    cor: '#131110',
    fundo: '#fffbe0',
    url: 'https://hifive-discos-landing.vercel.app',
  },
  {
    slug: 'amor',
    nome: 'Amor à Palavra',
    tipo: 'Landing page',
    cliente: 'Gabi Andrade, loja artesanal',
    local: 'Recife, PE',
    ano: 2026,
    resumo: 'Cadernos devocionais, planners e guias bíblicos feitos à mão, capa por capa.',
    desafio: 'Levar para a web o carinho de um produto artesanal vendido pelo Instagram, sem parecer um template genérico de loja.',
    entregas: [
      'Cores tiradas da logo oficial e motivo visual de caderno espiral desenhado em código',
      'Seções de produtos, guias bíblicos digitais e “como funciona” o pedido',
      'Pedidos direto pelo WhatsApp da loja',
      'Manual da marca e apresentação de slides para a reunião com a fundadora',
    ],
    stack: ['React', 'Vite', 'Tailwind CSS v4', 'Vercel'],
    paleta: ['#faf3e4', '#d8527d', '#cf9a4c', '#55231f'],
    fontes: 'Playfair Display · Caveat · Nunito',
    cor: '#d8527d',
    fundo: '#faf3e4',
    url: 'https://amorapalavra.vercel.app',
  },
  {
    slug: 'fj',
    nome: 'FJ Barbearia',
    tipo: 'Landing page',
    cliente: 'Barbearia tradicional com duas unidades',
    local: 'Monte Castelo, Fortaleza, CE',
    ano: 2026,
    resumo: 'Corte, barba e cuidado masculino — com agendamento a um toque de distância.',
    desafio: 'Uma barbearia nota 5,0 no Trinks precisava de uma vitrine à altura, que levasse o cliente direto à agenda.',
    entregas: [
      'Visual escuro com dourado e o poste de barbeiro como assinatura',
      'Botões de agendamento online e WhatsApp em destaque em toda a página',
      'Serviços, diferenciais, galeria, avaliações e mapa das duas unidades',
      'SEO local: título e descrição pensados para buscas no bairro',
    ],
    stack: ['React', 'Vite', 'Tailwind CSS', 'Vercel'],
    paleta: ['#14100d', '#1e1811', '#c9a227', '#f2e9dc'],
    fontes: 'Bebas Neue · Libre Franklin · JetBrains Mono',
    cor: '#c9a227',
    fundo: '#14100d',
    url: 'https://fj-barbearia.vercel.app',
  },
  {
    slug: 'blucookies',
    nome: 'Blu Cookies Box',
    tipo: 'Landing page',
    cliente: 'Loja de cookies artesanais',
    local: 'Fortaleza | Mossoró',
    ano: 2026,
    resumo: 'Cardápio, carrinho e pedido pronto no WhatsApp — o cookie que vai mudar a química do seu cérebro.',
    desafio: 'Uma loja que vendia pelo Instagram precisava receber pedidos organizados, sem pagar taxa de app de delivery e sem sair do WhatsApp que já usava.',
    entregas: [
      'Carrinho em etapas que monta a mensagem do pedido com itens, subtotal, entrega e contato',
      'Carrinho salvo no navegador: o pedido não se perde se a página fechar',
      'Endereço preenchido pelo CEP (ViaCEP) para entregas por Uber',
      'Visual azul da marca com o mascote Blu, pensado primeiro para o celular',
    ],
    stack: ['HTML', 'CSS', 'JavaScript', 'Vercel'],
    paleta: ['#f2f2f4', '#c9d3f0', '#3452a2', '#1e3272'],
    fontes: 'Fraunces · Archivo · Gochi Hand',
    cor: '#3452a2',
    fundo: '#f2f2f4',
    url: 'https://blu-cookies.vercel.app',
  },
  {
    slug: 'nestwise',
    nome: 'NestWise',
    tipo: 'Aplicação web',
    cliente: 'Produto próprio',
    local: 'Gestão de aluguéis',
    ano: 2026,
    resumo: 'App para quem aluga imóveis: unidades, inquilinos e pagamentos do mês num só lugar.',
    desafio: 'Evoluir um protótipo que guardava tudo no navegador para um app de verdade, com contas de usuário e dados sincronizados na nuvem.',
    entregas: [
      'Login com e-mail/senha e Google (Firebase Authentication)',
      'Banco de dados na nuvem (Firestore) isolado por usuário, com regras de segurança',
      'Cadastro de imóveis e unidades, e controle de pagamentos mês a mês',
      'Identidade visual própria: nome, logo, paleta e tipografia',
    ],
    stack: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'Firebase'],
    paleta: ['#f6f1e7', '#3f5d45', '#c1704a', '#2a2420'],
    fontes: 'Newsreader · Karla',
    cor: '#3f5d45',
    fundo: '#f6f1e7',
    url: null,
    status: 'Em desenvolvimento',
  },
  {
    slug: 'volver',
    nome: 'Volver',
    tipo: 'Aplicação web',
    cliente: 'Produto próprio',
    local: 'Plataforma devocional',
    ano: 2026,
    resumo: 'A mente, à luz da Palavra — reflexões interativas sobre livros e temas da Bíblia.',
    desafio: 'Construir uma plataforma de estudo que fosse acolhedora como um diário e organizada como uma biblioteca.',
    entregas: [
      'Biblioteca de livros, parábolas, salmos e trilhas temáticas com lições interativas',
      'Contas de usuário, diário pessoal, favoritos e versículo do dia',
      'Galeria de artes e conteúdo em mais de um idioma',
      'Mais de 150 versões publicadas, evoluindo com o uso',
    ],
    stack: ['HTML', 'CSS', 'JavaScript', 'Firebase', 'Vercel'],
    paleta: ['#12162a', '#1b2140', '#d9a441', '#e9e4d8'],
    fontes: 'Fraunces · IBM Plex Sans · IBM Plex Mono',
    cor: '#d9a441',
    fundo: '#12162a',
    url: null,
    status: 'Acesso restrito',
  },
]
